feat: Add gzip compression to Chronicle Exporter
observIQ/bindplane-agent pull request #1405
Opened 2024-01-03 20:40 UTC by Mrod1598

### Proposed Change

- Add gzip compression support to chronicle 

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

2024-01-03 21:33 UTC, BinaryFissionGames requested changes

2024-01-03 21:33 UTC, BinaryFissionGames commented on exporter/chronicleexporter/README.md
> +| `compression`       | string |                                                | `false`  | The compression type to use when sending logs. valid values are `none` and `gzip`           |
```suggestion
| `compression`       | string | `none`                                         | `false`  | The compression type to use when sending logs. valid values are `none` and `gzip`           |
```

2024-01-03 21:35 UTC, BinaryFissionGames approved these changes

2024-01-04 13:21 UTC, cpheps approved these changes

2024-01-04 13:58 UTC, merged