fix(OPTIONAL): fix install_unix.sh breaking with return code 2 in non-interactive environments
observIQ/bindplane-agent pull request #1813
Opened 2024-08-24 13:51 UTC by dithmer

### Proposed Change
The script "install_unix.sh" was not working in non-interactive shells, because there are tools used (stty and tput) for which a connected tty is mandatory. This is being fixed by a sh-compliant way of checking if the `$-` contains the `i`-flag.

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

2024-08-24 13:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/observIQ/bindplane-agent?pullRequest=1813) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/observIQ/bindplane-agent?pullRequest=1813) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/observIQ/bindplane-agent?pullRequest=1813) it.</sub>

2024-08-26 17:37 UTC, BinaryFissionGames requested changes

2024-08-26 17:37 UTC, BinaryFissionGames commented on scripts/install/install_unix.sh
> +
This seems to always be false in the environment I'm testing in 🤔 

For reference, I'm testing in a fresh Ubuntu Server 24.04 install. The exiting with status code 2 issue is fixed, but we don't get the coloring like we should.

2024-10-02 20:02 UTC, Dylan-M commented
I suggest closing this in favor of #1895

2024-10-23 15:54 UTC, BinaryFissionGames commented
I'm going to close this since #1895 has been merged and should solve this problem with an optional flag. Thanks for taking the time to open this PR, it's very much appreciated!

2024-10-23 15:54 UTC, closed without merging