chore: Update documentation
observIQ/bindplane-agent pull request #1912
Opened 2024-10-14 17:34 UTC by dpaasman00

### Proposed Change

Updates repo documentation to be supervisor/v2 oriented.

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

2024-10-24 18:33 UTC, BinaryFissionGames requested changes
Content looks good, just a small grammatical mistake I found here

2024-10-24 18:33 UTC, BinaryFissionGames commented on docs/installation-mac.md
> +The supervisor remembers the last config it received via OpAMP and always starts rewrites the agent's config file with it when it starts. This means you can't manually edit the agent's config file on
```suggestion
The supervisor remembers the last config it received via OpAMP and always rewrites the agent's config file with it when it starts. This means you can't manually edit the agent's config file on disk. The best way to modify the configuration is to send a new one from the OpAMP platform the supervisor is connected to.
```

2024-10-24 19:46 UTC, BinaryFissionGames approved these changes

2024-10-25 13:06 UTC, colelaven approved these changes

2024-10-25 13:06 UTC, merged