Justin/bpop 847 support namespace and ingestion labels
observIQ/bindplane-agent pull request #1939
Opened 2024-10-30 18:27 UTC by justinianvoss22

### Proposed Change
- Update chronicle exporter to be able to take namespace and ingestion labels from attributes if present.
- Make logType not required

### Testing
- Unit testing
- Testing agent on local BP

##### Checklist
- [ x ] Changes are tested
- [ x ] CI has passed

2024-11-01 13:07 UTC, jsirianni commented
I updated the PR name, it will help w/ release notes. Feel free to tweak it if its incorrect.

2024-11-04 18:05 UTC, kuiperda commented
Took a quick high level pass and it makes sense to me, will let Dakota review though.

2024-11-04 19:17 UTC, dpaasman00 requested changes
First pass and generally looks good. Somethings to address however.

2024-11-04 19:17 UTC, dpaasman00 commented on exporter/chronicleexporter/marshal.go
>  type protoMarshaler struct {
Since we're using dynamic labels, the `labels` object on this struct is no longer used and should be removed.

2024-11-04 19:17 UTC, dpaasman00 commented on exporter/chronicleexporter/marshal.go
> +				}
I think some more thought needs to go into how these labels get added. Currently we append all labels present on a log record to the overarching map, regardless of if they're already present. This causes repeat entries if there are multiple log records with the same labels. You can add this test case to the test `TestProtoMarshaler_MarshalRawLogs` in `marshal_test.go` test to see this behavior:
```go
{
			name: "Multiple log records with attributes",
			cfg: Config{
				CustomerID:      uuid.New().String(),
				LogType:         "WINEVTLOG",
				Namespace:       "test",
				RawLogField:     "body",
				OverrideLogType: false,
			},
			labels: []*api.Label{},
			logRecords: func() plog.Logs {
				logs := plog.NewLogs()
				record1 := logs.ResourceLogs().AppendEmpty().ScopeLogs().AppendEmpty().LogRecords().AppendEmpty()
				record1.Body().SetStr("First log message")
				record1.Attributes().FromRaw(map[string]any{`chronicle_ingestion_label["key1"]`: "value1", `chronicle_ingestion_label["key2"]`: "value2"})
				record2 := logs.ResourceLogs().AppendEmpty().ScopeLogs().AppendEmpty().LogRecords().AppendEmpty()
				record2.Body().SetStr("Second log message")
				record2.Attributes().FromRaw(map[string]any{`chronicle_ingestion_label["key1"]`: "value1", `chronicle_ingestion_label["key2"]`: "value2"})
				return logs
			},
			expectations: func(t *testing.T, requests []*api.BatchCreateLogsRequest) {
				require.Len(t, requests, 1, "Expected a single batch request")
				batch := requests[0].Batch
				// verify batch source labels
				require.Len(t, batch.Source.Labels, 2)
				require.Len(t, batch.Entries, 2, "Expected two log entries in the batch")
				// Verifying the first log entry data
				require.Equal(t, "First log message", string(batch.Entries[0].Data))
				// Verifying the second log entry data
				require.Equal(t, "Second log message", string(batch.Entries[1].Data))
			},
		},
```

2024-11-04 19:17 UTC, dpaasman00 commented on exporter/chronicleexporter/marshal_test.go
I think there are some more test cases that can be added to thoroughly test this new functionality and potential edge cases, such as the multiple log records example I gave in an earlier comment.

2024-11-04 19:17 UTC, dpaasman00 commented on exporter/chronicleexporter/marshal.go
This is a general, very nit comment. Unless you feel strongly about it, there are several deleted new lines in this PR that I think should be restored to help with readability. Just take a look through the diff here to find them.

2024-11-04 19:17 UTC, dpaasman00 commented on exporter/chronicleexporter/marshal.go
>  		startTime:    time.Now(),
Contrary to the deleted newlines comment I left, this is a valid deleted new line and should stay deleted.

2024-11-08 19:00 UTC, dpaasman00 commented on exporter/chronicleexporter/marshal.go
> +}
Again, the return value isn't used when there's an error, so return an empty slice and simplify this code a bit
```suggestion
func (m *protoMarshaler) getIngestionLabels(logRecord plog.LogRecord) ([]*api.Label, error) {
	// check for labels in attributes["chronicle_ingestion_labels"]
	ingestionLabels, err := m.getRawNestedFields(chronicleIngestionLabelsPrefix, logRecord)
	if err != nil {
		return []*api.Label{}, fmt.Errorf("get chronicle ingestion labels: %w", err)
	}
	if len(ingestionLabels) != 0 {
		return ingestionLabels, nil
	}

	// use labels defined in config if needed
	configLabels := make([]*api.Label, 0)
	for key, value := range m.cfg.IngestionLabels {
		configLabels = append(configLabels, &api.Label{
			Key:   key,
			Value: value,
		})
	}

	return configLabels, nil
}
```

2024-11-08 19:06 UTC, dpaasman00 commented on exporter/chronicleexporter/marshal.go
> +	}
No need to return nil instead of an empty `[]*api.Label`

```suggestion
```

2024-11-08 19:13 UTC, dpaasman00 commented on exporter/chronicleexporter/marshal.go
I know your PR doesn't touch the `getLogType()` function, but in the spirit of adding 2 similar funcs, can you update `getLogType()` to return an empty string in the 2 cases it returns an error, because the returned string does not get used when there's an error

2024-11-11 13:55 UTC, dpaasman00 commented on exporter/chronicleexporter/README.md
> +If there are nested fields in `attributes["chronicle_ingestion_label"]`, we will use the values in the payload.
These should be broken out into a separate section from the "Log Type" section they're in currently, something like "Namespace & Ingestion Labels". Also state that if the attribute fields are present, they are used regardless of the value in the config.

2024-11-11 14:05 UTC, dpaasman00 requested changes
Couple more thoughts, otherwise this is looking good. Going to test next.

2024-11-11 14:05 UTC, dpaasman00 commented on exporter/chronicleexporter/marshal.go
> +				}
This should also check if the namespace is empty before adding
```suggestion
                         if namespace != "" {
				// each logType maps to exactly 1 namespace value
				if _, ok := namespaceMap[logType]; !ok {
					namespaceMap[logType] = namespace
				}
			}
```

2024-11-12 12:23 UTC, dpaasman00 approved these changes
This has been working well for me.

2024-11-12 15:07 UTC, merged