feat: unroll processor
observIQ/bindplane-agent pull request #2021
Opened 2024-12-02 21:40 UTC by schmikei

### Proposed Change
Still need to write some documentation on this but the idea is to create new log entries out of arrays. The start of this is working exclusively with the body of a log entry.

Sample config

```yaml
receivers:
  filelog:
    include: [ ./test.json ]
    start_at: beginning
  filelog/2:
    include: [ ./test2.json ]
    start_at: beginning
processors:
  transform:
    log_statements:
      - context: log
        statements:
          - set(body, Split(body, "\\n"))
          # - unroll(body)
  transform/split-by-comma:
    log_statements:
      - context: log
        statements:
          - set(body, Split(body, ","))
  transform/set-attr:
    log_statements:
      - context: log
        statements:
          - set(attributes["owner"], "Keith")
  unroll:
  unroll/body:
    unroll_key: ""

exporters:
  file:
    path: ./test/output.json
  debug:
    verbosity: detailed
  googlecloud/otel-agent-dev:
    log:
        compression: gzip
        default_log_name: Keiths-Macbook-Pro.local
        resource_filters:
            - regex: .*
    metric:
        compression: gzip
    project: otel-agent-dev

service:
  pipelines:
    # logs:
    #   receivers: [filelog]
    #   processors: [transform, unroll]
    #   exporters: [debug, file, googlecloud/otel-agent-dev]
    logs/2:
      receivers: [filelog/2]
      processors: [transform/split-by-comma, unroll/body, transform/set-attr]
      exporters: [debug, file, googlecloud/otel-agent-dev]
```

This for example can take in a log file like this

```
1,2,3,4,5,6,7,8
```

And it becomes multiple log events:

<img width="1290" alt="image" src="https://github.com/user-attachments/assets/b7893979-38df-4660-aca4-14816671d157">

##### Checklist
- [ ] Changes are tested
- [ ] CI has passed

2024-12-02 22:04 UTC, djaglowski commented on processor/unrollprocessor/processor.go
> +	newLogs := plog.NewLogs()
Why do we need to create a new one? Can't we just move log records around within each `LogRecordSlice`?

2024-12-02 22:04 UTC, djaglowski commented on processor/unrollprocessor/processor.go
> +		p.siftLogRecords(l).CopyTo(scopeLogs.LogRecords())
Same - if we're not unrolling anything on the scope, we shouldn't need to copy or change it in any way. Just drill in and work on the `LogRecordSlice` it contains.

2024-12-02 22:04 UTC, djaglowski commented on processor/unrollprocessor/processor.go
> +	newLogRecords := plog.NewLogRecordSlice()
We shouldn't need to create a new copy of this. Just modify the existing one.

2024-12-03 19:33 UTC, dpaasman00 requested changes
Couple nits + what I messaged you on the side about

2024-12-03 20:31 UTC, dpaasman00 approved these changes
Looking good!

2024-12-03 20:34 UTC, merged

2024-12-04 18:03 UTC, tharkhay4 reviewed
Leaves